# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'countdown.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import time
from PyQt5 import QtCore, QtGui, QtWidgets
import keyboard


class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(344, 133)
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.textbox = QtWidgets.QLineEdit(self.centralwidget)
        self.textbox.setGeometry(QtCore.QRect(10, 10, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.textbox.setFont(font)
        self.textbox.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.textbox.setText("0")
        self.textbox.setObjectName("textbox")
        self.textbox.setReadOnly(True)
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setGeometry(QtCore.QRect(10, 70, 321, 41))
        self.button.setObjectName("button")
        window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(window)
        self.statusbar.setObjectName("statusbar")
        window.setStatusBar(self.statusbar)
        
        self.button.clicked.connect(lambda: self.checker(self.textbox.text()))
        # keyboard.add_hotkey('Return', self.checker, args=(self.textbox.text()))

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "CountDown"))
        self.textbox.setPlaceholderText(_translate("window", "Enter amount of seconds"))
        self.button.setText(_translate("window", "Start"))
        self.button.setShortcut(_translate("window", "Return"))
        
    def checker(self, seconds):
        if seconds.isdigit():
            seconds = int(seconds)
            # hour, minute, second = self.set_clock(seconds)
            # while hour > 0 or minute > 0 or second > 0:
            #     time.sleep(1)
            #     hour, minute, second = self.set_clock(seconds)
            #     self.textbox.setText(f"{str(hour).zfill(2)}:{str(min).zfill(2)}:{str(second).zfill(2)}")
            seconds += 1
            self.textbox.setText(f"{str(seconds)}")
        
    # def set_clock(self,seconds):
    #     hour = seconds // 3600
    #     minute = (seconds - (hour * 3600)) // 60
    #     second = seconds - ((hour * 3600) + (minute * 60))
        
    #     return hour, minute, seconds
         


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_window()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
